services:
  laravel:
    container_name: laravel-api
    build: 
      context: ./api
    ports:
      - 8080:80

  vue:
    container_name: vue-app
    build:
      context: ./app
    ports:
      - 3000:3000
