FROM node:lts-slim AS base

# pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .

FROM base AS build

RUN pnpm run build

FROM node:lts-alpine AS prod

WORKDIR /app

COPY --from=build /app/dist ./dist

# also not the best way to serve static files
#  so not production ready
RUN npm install -g vite

CMD vite preview --host --port 3000

EXPOSE 3000
