FROM node:lts-slim AS base

# pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .

FROM base

COPY .env.example .env.local

RUN pnpm run build

# not the best way to serve static files
#  so not production ready
CMD pnpm run preview --host --port 3000

EXPOSE 3000
