FROM composer:lts AS dependencies

COPY composer.json composer.lock /app/

WORKDIR /app

RUN composer install --prefer-dist --no-dev --optimize-autoloader --no-interaction --no-autoloader

# by far the easiest way to do this
#  obviously it is not ready to production
FROM dunglas/frankenphp AS runtime

COPY . /app

WORKDIR /app

COPY --from=composer:lts /usr/bin/composer /usr/local/bin/composer
COPY --from=dependencies /app/vendor vendor
RUN composer dump-autoload --optimize --no-dev

COPY .env.example .env

# enable production
ENV APP_ENV=production
ENV APP_DEBUG=false

RUN php artisan migrate --force
RUN php artisan db:seed --force

# RUN php artisan optimize
RUN php artisan config:cache

CMD frankenphp php-server -r public/
